version: '3.8'
## HOPE THIS WORKS
services:
  app:
    build: .
    env_file: .env.production

    environment:
      - NODE_ENV=production
      - PORT=3000

    expose:
      - "3000"

  
    networks:
      - coolify

    labels:
      - "traefik.enable=true"
      
      
      - "traefik.http.routers.$$COOLIFY_CONTAINER_NAME.rule=Host(`alchemize.hackclub.com`)"
      - "traefik.http.routers.$$COOLIFY_CONTAINER_NAME.entrypoints=websecure"
      - "traefik.http.routers.$$COOLIFY_CONTAINER_NAME.tls=true"
      
      
      - "traefik.http.services.$$COOLIFY_CONTAINER_NAME.loadbalancer.server.port=3000"

networks:
  coolify:
    external: true
